export class SAMPLES{
    srjno = null;
    gactnumber = null;
    gaanalysis = null;
    gadate = null;
    gatime = null;
    gablood = null;
    galiver = null;
    gasuspectedpoison = null;
    gaurine = null;
    gakidney = null;
    gamedicine = null;
    gabile = null;
    galungs = null;
    gaother = null;
    gastomach =null;
    gavitreous = null;
    gaintestinal = null;
    gabrain = null;
    mrirefnum = null;
    mrianalysis = null;
    mridate = null;
    mritime = null;
    mriblood = null;
    mriliver = null;
    mrisuspectedpoison = null;
    mriurine = null;
    mrikidney = null;
    mrimedicine = null;
    mribile = null;
    mrilungs = null;
    mriother = null;
    mristomach =null;
    mrivitreous = null;
    mriintestinal = null;
    mribrain = null;
    otherrefnum = null;
    otheranalysis = null;
    otherdate = null;
    othertime = null;
    otherblood = null;
    otherliver = null;
    othersuspectedpoison = null;
    otherurine = null;
    otherkidney = null;
    othermedicine = null;
    otherbile = null;
    otherlungs = null;
    otherother = null;
    otherstomach =null;
    othervitreous = null;
    otherintestinal = null;
    otherbrain = null;

    constructor(srjno, 
        gactnumber,
        gaanalysis,
        gadate ,
        gatime ,
        gablood,
        galiver,
        gasuspectedpoison,
        gaurine,
        gakidney,
        gamedicine,
        gabile,
        galungs,
        gaother,
        gastomach,
        gavitreous,
        gaintestinal,
        gabrain,
        mrirefnum,
        mrianalysis,
        mridate,
        mritime,
        mriblood,
        mriliver,
        mrisuspectedpoison,
        mriurine,
        mrikidney,
        mrimedicine,
        mribile,
        mrilungs,
        mriother,
        mristomach,
        mrivitreous,
        mriintestinal,
        mribrain,
        otherrefnum,
        otheranalysis,
        otherdate,
        othertime,
        otherblood,
        otherliver,
        othersuspectedpoison,
        otherurine,
        otherkidney,
        othermedicine,
        otherbile,
        otherlungs,
        otherother,
        otherstomach,
        othervitreous,
        otherintestinal,
        otherbrain ){
            this.srjno = srjno;
            this.gactnumber = gactnumber;
            this.gaanalysis = gaanalysis;
            this.gadate = gadate;
            this.gatime = gatime;
            this.gablood = gablood;
            this.galiver = galiver;
            this.gasuspectedpoison = gasuspectedpoison;
            this.gaurine = gaurine;
            this.gakidney = gakidney;
            this.gamedicine = gamedicine;
            this.gabile = gabile;
            this.galungs = galungs;
            this.gaother = gaother;
            this.gastomach = gastomach;
            this.gavitreous = gavitreous;
            this.gaintestinal = gaintestinal;
            this.gabrain = gabrain;
            this.mrirefnum = mrirefnum;
            this.mrianalysis = mrianalysis;
            this.mridate = mridate;
            this.mritime = mritime;
            this.mriblood = mriblood;
            this.mriliver = mriliver;
            this.mrisuspectedpoison = mrisuspectedpoison;
            this.mriurine = mriurine;
            this.mrikidney = mrikidney;
            this.mrimedicine = mrimedicine;
            this.mribile = mribile;
            this.mrilungs = mrilungs;
            this.mriother = mriother;
            this.mristomach = mristomach;
            this.mrivitreous = mrivitreous;
            this.mriintestinal = mriintestinal;
            this.mribrain = mribrain;
            this.otherrefnum = otherrefnum;
            this.otheranalysis = otheranalysis;
            this.otherdate = otherdate;
            this.othertime = othertime;
            this.otherblood = otherblood;
            this.otherliver = otherliver;
            this.othersuspectedpoison = othersuspectedpoison;
            this.otherurine = otherurine;
            this.otherkidney = otherkidney;
            this.othermedicine = othermedicine;
            this.otherbile = otherbile;
            this.otherlungs = otherlungs;
            this.otherother = otherother;
            this.otherstomach = otherstomach;
            this.othervitreous = othervitreous;
            this.otherintestinal = otherintestinal;
            this.otherbrain = otherbrain;
        }
    
}